ALTER TABLE plans ALTER COLUMN features DROP DEFAULT;
ALTER TABLE plans ALTER COLUMN features DROP NOT NULL;
ALTER TABLE plans ALTER COLUMN features TYPE text[] USING ARRAY[]::text[];
ALTER TABLE plans ALTER COLUMN features SET DEFAULT ARRAY[]::text[];
