ALTER TABLE plans ALTER COLUMN features DROP DEFAULT;
ALTER TABLE plans ALTER COLUMN features DROP NOT NULL;
ALTER TABLE plans ALTER COLUMN features TYPE jsonb USING '{}'::jsonb;
ALTER TABLE plans ALTER COLUMN features SET DEFAULT '{}'::jsonb;
ALTER TABLE plans ALTER COLUMN features SET NOT NULL;
